title: Video Toolkit
description: A fast and efficient command-line tool for trimming MP4 videos with minimal processing and automatic audio extraction
url: https://nipunbatra.github.io/video-toolkit
baseurl: /video-toolkit
show_excerpts: false

# Jekyll configuration
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages configuration
repository: nipunbatra/video-toolkit
github:
  repository_url: https://github.com/nipunbatra/video-toolkit

# Site settings
author:
  name: Nipun Batra
  email: nipun.batra@gmail.com

# SEO settings
logo: /assets/images/logo.png
twitter:
  username: nipunbatra
  card: summary

# Cayman theme configuration
cayman:
  github_ribbon: true
  google_analytics: false

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - .git/

# Include
include:
  - _pages
  - README.md